locations = [
'Audubon Place'
,'Baronne Street'
,'Basin Street'
,'Bayou Road'
,'Bienville Street'
,'Bourbon Street'
,'Broad Street'
,'Burgundy Street'
,'Calliope Street'
,'Camp Street'
,'Canal Boulevard'
,'Canal Street'
,'Carondelet Street'
,'Carrollton Avenue'
,'Chartres Street'
,'City Park Avenue'
,'Claiborne Avenue'
,'Conti Street'
,'Dante Street'
,'Dauphine Street'
,'Decatur Street'
,'Desire Street'
,'Dryades Street'
,'Dumaine Street'
,'Earhart Expressway'
,'Elysian Fields Avenue'
,'Esplanade Avenue'
,'Exchange Place'
,'Felicity Street'
,'Freret Street'
,'Frenchmen Street'
,'Gayoso Street'
,'Gentilly Boulevard'
,'Girod Street'
,'Gravier Street'
,'Henry Clay Avenue'
,'Howard Avenue'
,'Iberville Street'
,'Jackson Avenue'
,'Jeff Davis Parkway'
,'Julia Street'
,'Lafayette Street'
,'Lakeshore Drive'
,'Lee Circle'
,'Louisiana Avenue'
,'Lowerline Street'
,'Loyola Avenue'
,'Magazine Street'
,'Magnolia Street'
,'Marengo Street'
,'Martin Luther King Jr. Boulevard'
,'McAlister Place'
,'Napoleon Avenue'
,'Oak Street'
,'Oretha Castle Haley Boulevard'
,'Orleans Street'
,'Pearl Street'
,'Peters Street'
,'Pontchartrain Expressway'
,'Poydras Street'
,'Prytania Street'
,'Rampart Street'
,'Robert E. Lee Boulevard'
,'Royal Street'
,'Simon Bolivar Avenue'
,'St. Ann Street'
,'St. Charles Avenue'
,'St. Claude Avenue'
,'St. Louis Street'
,'St. Peter Street'
,'St. Philip Street'
,'Tchoupitoulas Street'
,'Toulouse Street'
,'Barringer Foreman Rd'
,'Barringer Rd'
,'Barrosa Way'
,'Barrow Dr'
,'Barry Dr'
,'Bartlett St'
,'Baskins Cir'
,'Bassett Dr'
,'Batavia Ave'
,'Bateman Cir'
,'Baton Rouge Ave'
,'Baton Rouge Ct'
,'Bawell St'
,'Bay Ridge Ct'
,'Bay St'
,'Bayberry Ave'
,'Baylor Dr'
,'Baynard St'
,'Bayou Dr'
,'Bayou Fountain Ave'
,'Bayridge Dr'
,'Bayside Ave'
,'Baytree Dr'
,'Baywood Ave'
,'Bazaar Ave'
,'Bea Dr'
,'Beachwood Ave'
,'Beachwood Dr'
,'Beaconwood Dr'
,'Beau Darren Dr'
,'Beaujolaes Ave'
,'Beaumont Dr'
,'Beauregard St'
,'Beauverde Ct'
,'Beckenham Dr'
,'Beckfield Ave'
,'Becky Lee Dr'
,'Bedford Dr'
,'Beech Harbor Ave'
,'Beech St'
,'Beechgrove Dr'
,'Beechwood Dr'
,'Bel Air Dr'
,'Bel Meadow Ave'
,'Belcaro Dr'
,'Beldart Ct'
,'Belfast Dr'
,'Bella Dr'
,'Bellarbor Dr'
,'Belle Angela Ave'
,'Belle Brittany Ave'
,'Belle Cherie Ave'
,'Belle Christi Dr'
,'Belle Famille Ave'
,'Bonnie Dr'
,'Bonnie Jean Dr'
,'Bontura Ct'
,'Booker St'
,'Boone Ave'
,'Bootsie Dr'
,'Bordeaux Dr'
,'Boreas Dr'
,'Boston St'
,'Bourbon Ave'
,'Bourgeois St'
,'Bowie Ave'
,'Bowman Ave'
,'Boyce Dr'
,'Boyd Ave'
,'Boylan Ave'
,'Bozeman Ave'
,'Bracewell Dr'
,'Braddock St'
,'Braden Patrick Dr'
,'Bradfield Ave'
,'Bradley St'
,'Bradmore Dr'
,'Brady St'
,'Braeburn Dr'
,'Braewood Ave'
,'Brakley Dr'
,'Bramble Dr'
,'Brame Dr'
,'Branchwood Ave'
,'Brandon Dr'
,'Brandon Lynn Dr'
,'Brandywine Dr'
,'Brashears St'
,'Breckenridge Ave'
,'Breman Dr'
,'Brent Ave'
,'Brent Ct'
,'Brentwood Dr'
,'Brentwood Dr'
,'Breton Blvd'
,'Breton Dr'
,'Bretshire Dr'
,'Brett Pl'
,'Brewster Ave'
,'Brianna Ave'
,'Briar Hollow Ave'
,'Briarlake Ave'
,'Briarplace Dr'
,'Briartrail Dr'
,'Briarwood Pl'
,'Brice St'
,'Bricksome Ave'
,'Brickyard Ln'
,'Brierwood Dr'
,'Brighton Ave'
,'Brightside Dr'
,'Brightside View Dr'
,'Brightview Ct'
,'Brillock Ave'
,'Bringhurst Ave'
,'Brinwood Ave'
,'Bristoe Ave'
,'Bristol Ave'
,'Britain Ave'
,'Brittany Dr'
,'Brittmore Ave'
,'Broad Magnolia Ct'
,'Broadmoor Ave'
,'Broadmoor Cir'
,'Broadmoor Ct'
,'Broadway St'
,'Brocade Dr'
,'Brocato Ave'
,'Brogdon Ln'
,'Brogdon Ln'
,'Broker Ave'
,'Bromley Dr'
,'Bronco Ave'
,'Bronzebush Ave'
,'Brook Spring Ave'
,'Brookcrest Ave'
,'Brookfield Ave'
,'Brookhaven Dr'
,'Brooklawn Dr'
,'Brookline Ave'
,'Brookmeade Dr'
,'Brooks Ave'
,'Brookshire Ave'
,'Brookwood Dr'
,'Broussard St'
,'Brownfields Dr'
,'Browning Dr'
,'Brownlee St'
,'Brownway Ln'
,'Bruce Alley'
,'Brunswick Ave'
,'Brutus Dr'
,'Bryans Crossing Ave'
,'Bryant Dr'
,'Buckeye Dr'
,'Buckingham Ave'
,'Buckley Ave'
,'Buena Vista Dr'
,'Buhler Dr'
,'Bull Run Dr'
,'Bungalow Ln'
,'Bunker Hill Dr'
,'Cabernet Dr'
,'Cable St'
,'Cabot Ave'
,'Caddo St'
,'Cadillac St'
,'Caesar Ave'
,'Cain St'
,'Cal Rd'
,'Calanne Ave'
,'Caldwell Ave'
,'California St'
,'Calion Dr'
,'Callahan St'
,'Calumet St'
,'Calverton Dr'
,'Cambridge St'
,'Camden St'
,'Camelia Ave'
,'Camelia Trace Dr'
,'Camelia Way Ct'
,'Camelio Ave'
,'Camelot Ave'
,'Cameo Ct'
,'Cameron Ave'
,'Cammy Ave'
,'Campanile Ct'
,'Campbell Dr'
,'Camphor Dr'
,'Campus Lake Rd'
,'Canada St'
,'Canal St'
,'Candace St'
,'Candlewood Ave'
,'Canebrake Dr'
,'Cannon St'
,'Canonicus St'
,'Canosa Ct'
,'Canterbury Dr'
,'Canterdale Ave'
,'Canyonland Dr'
,'Cape Hart Ct'
,'Cape Hatteras Dr'
,'Capistra Dr'
,'Capital Heights Ave'
,'Capitol Access Rd'
,'Capitol Ave'
,'Capitol Lake Dr'
,'Capri Dr'
,'Caprice Dr'
,'Cardeza Ave'
,'Cardiff Ave'
,'Cardigan Ave'
,'Cardinal St'
,'Carl Ave'
,'Monrovia St'
,'Montbard Ave'
,'Montclair Ct'
,'Nancy Dr'
,'Napoleon St'
,'Nashville Ave'
,'Nassau Dr'
,'Natalbany Ave'
,'Navajo St'
,'Nebraska St'
,'Ned Ave'
,'Needham Dr'
,'Nehru Ave'
,'Nellie Ave'
,'Nelson Dr'
,'Nelwyn Dr'
,'Neosho Ave'
,'Netterville St'
,'New Market Dr'
,'New Rafe Meyer Rd'
,'New Wood Ave'
,'Perkins Rd'
,'Perkins Rd'
,'Pershing Dr'
,'Perthshire Dr'
,'Petersburg Dr'
,'Phaeton Crossing Dr'
,'Phebus Dr'
,'Phelps St'
,'Phillips Ave'
,'Phillips Rd'
,'Phlox Ave'
,'Physicians Park Dr'
,'Picardy Ave'
,'Pickett Ave'
,'Pierce Ave'
,'Pikes Ln'
,'Pimpernel Ave'
,'Pin Oak St'
,'Pine Cone Ct'
,'Pine Crest Dr'
,'Pine Hill Dr'
,'Pine Hollow Ct'
,'Pine Island Ave'
,'Pine Moss Dr'
,'Pine Park Dr'
,'Pine Ridge Dr'
,'Pine Thicket Dr'
,'Pine Tree Dr'
,'Pinebrook Ave'
,'Pinedale Ave'
,'Pinehurst Ave'
,'Pinnacle Ave'
,'Pino St'
,'Pintail St'
,'Pioneer Dr'
,'Pipestone Dr'
,'Pitcairn Dr'
,'Pitcher St'
,'Pittsburg Ave'
,'Plantation Ct'
,'Plantation Dr'
,'Plantation Key Dr'
,'Plantation Ln'
,'Platt Dr'
,'Plaza Americana Dr'
,'Plaza Dr'
,'Plaza Tower Dr'
,'Pleasant Point Blvd'
,'Pleasant Ridge St'
,'Pliny St'
,'Plover St'
,'Plum Broque Dr'
,'Pluskat Ave'
,'Plymouth Dr'
,'Pocahontas St'
,'Pocasset St'
,'Poinsettia Dr'
,'Point Avery Dr'
,'Point Chenier Ave'
,'Point Clear Dr'
,'Pointer Ct'
,'Poirier Pl'
,'Polarine Ave'
,'Pollard Pkwy'
,'Polo Ave'
,'Polytech Dr'
,'Pompey Dr'
,'Ponderosa Dr'
,'Pontiac St'
,'Sugarland Dr'
,'Sullivan Rd'
,'Sully Dr'
,'Sumerulos St'
,'Summa Ave'
,'Summa Ct'
,'Summer Breeze Dr'
,'Summer Dr'
,'Summer Grove Ave'
,'Summer Lake Dr'
,'Summerdale Dr'
,'Summerleaf Cir'
,'Summers Rd'
,'Summerwood Ave'
,'Summit Ridge Dr'
,'Sumrall Dr'
,'Sun Belt Ct'
,'Sunbury Cir'
,'Suncrest Ave'
,'Suncrest Ct'
,'Sunny Cline Dr'
,'Sunnybrook Dr'
,'Sunnyhill Ave'
,'Sunray Ave'
,'Sunset Blvd'
,'Sunset Hill Ave'
,'Sunset Point Ct'
,'Sunshine Park Ct'
,'Sunshine Rd'
,'Superior Dr'
,'Superior Dr'
,'Surrey Ct Ave'
,'Surrey Dr'
,'Susan Ave'
,'Sussex St'
,'Sutton Dr'
,'Svendson Dr'
,'Swan Ave'
,'Swart St'
,'Sweet Gum Ave'
,'Sweet Olive Ave'
,'Sweet Olive Ave'
,'Sweetbriar St'
,'Sweetbrook Ave'
,'Sweetleaf St'
,'Sweetwood Ct'
,'Swire Ave'
,'Syble Dr'
,'Sycamore St'
,'Sylvan Dr'
,'Taft St'
,'Tall Oaks Ct'
,'Tall Oaks Dr'
,'Tall Timbers Rd'
,'Tallow Dr'
,'Tallwood Dr'
,'Tallyho Ave'
,'Talton Ave'
,'Tamari Dr'
,'Tamarix St'
,'Tams Dr'
,'Tanglewood Dr'
,'Tanner St'
,'Tanwood Ave'
,'Tara Blvd'
,'Tarrytown Ave'
,'Tartan Dr'
,'Taylor St'
,'Teal St'
,'Terrell Rd'
,'Terry Dr'
,'Tezcucco Dr'
,'Thad Cain Ln'
,'Thelma St'
,'Theodosia Dr'
,'Thibodeaux Ave'
,'Thistle Ridge Dr'
,'Thomas H Delpit Dr'
,'Thomas Rd'
,'Thoreau Dr'
,'Thornwood Dr'
,'Ticonderoga Ave'
,'Tide Dr'
,'Wildwood Pkwy'
,'Willard St'
,'Williams Alley'
,'Williams St'
,'Williamsburg Dr'
,'Williamson St'
,'Willow Bay Dr'
,'Willow Glen Dr'
,'Willow Grove Dr'
,'Willow Oak Ave'
,'Willow Springs Ave'
,'Willow St'
,'Willow View Ave'
,'Willowbrook Ct'
,'Willowbrook Dr'
,'Wilmot St'
,'Wilshire Dr'
,'Wilton Dr'
,'Wiltz Dr'
,'Wimpole St'
,'Winbourne Ave'
,'Winchester Ave'
,'Windermere Oaks Ct'
,'Windfall Ct'
,'Winding Lake Ave'
,'Windrift St'
,'Windrush Way'
,'Windsong Dr'
,'Windsor Dr'
,'Windwood Dr'
,'Windy Ridge Ave'
,'Wingate Dr'
,'Winn Ave'
,'Winnebago St'
,'Winnipeg Dr'
,'Winter Ave'
,'Winter Ridge Ave'
,'Younger Ave'
];