locations = [
'Audubon Place'
,'Baronne Street'
,'Basin Street'
,'Bayou Road'
,'Bienville Street'
,'Bourbon Street'
,'Broad Street'
,'Burgundy Street'
,'Calliope Street'
,'Camp Street'
,'Canal Boulevard'
,'Canal Street'
,'Carondelet Street'
,'Carrollton Avenue'
,'Chartres Street'
,'City Park Avenue'
,'Claiborne Avenue'
,'Conti Street'
,'Dante Street'
,'Dauphine Street'
,'Decatur Street'
,'Desire Street'
,'Dryades Street'
,'Dumaine Street'
,'Earhart Expressway'
,'Elysian Fields Avenue'
,'Esplanade Avenue'
,'Exchange Place'
,'Felicity Street'
,'Freret Street'
,'Frenchmen Street'
,'Gayoso Street'
,'Gentilly Boulevard'
,'Girod Street'
,'Gravier Street'
,'Henry Clay Avenue'
,'Howard Avenue'
,'Iberville Street'
,'Jackson Avenue'
,'Jeff Davis Parkway'
,'Julia Street'
,'Lafayette Street'
,'Lakeshore Drive'
,'Lee Circle'
,'Louisiana Avenue'
,'Lowerline Street'
,'Loyola Avenue'
,'Magazine Street'
,'Magnolia Street'
,'Marengo Street'
,'Martin Luther King Jr. Boulevard'
,'McAlister Place'
,'Napoleon Avenue'
,'Oak Street'
,'Oretha Castle Haley Boulevard'
,'Orleans Street'
,'Pearl Street'
,'Peters Street'
,'Pontchartrain Expressway'
,'Poydras Street'
,'Prytania Street'
,'Rampart Street'
,'Robert E. Lee Boulevard'
,'Royal Street'
,'Simon Bolivar Avenue'
,'St. Ann Street'
,'St. Charles Avenue'
,'St. Claude Avenue'
,'St. Louis Street'
,'St. Peter Street'
,'St. Philip Street'
,'Tchoupitoulas Street'
,'Toulouse Street'
,'Barringer Foreman Rd'
,'Barringer Rd'
,'Barrosa Way'
,'Barrow Dr'
,'Barry Dr'
,'Bartlett St'
,'Baskins Cir'
,'Bassett Dr'
,'Batavia Ave'
,'Bateman Cir'
,'Baton Rouge Ave'
,'Baton Rouge Ct'
,'Bawell St'
,'Bay Ridge Ct'
,'Bay St'
,'Bayberry Ave'
,'Baylor Dr'
,'Baynard St'
,'Bayou Dr'
,'Bayou Fountain Ave'
,'Bayridge Dr'
,'Bayside Ave'
,'Baytree Dr'
,'Baywood Ave'
,'Bazaar Ave'
,'Bea Dr'
,'Beachwood Ave'
,'Beachwood Dr'
,'Beaconwood Dr'
,'Beau Darren Dr'
,'Beaujolaes Ave'
,'Beaumont Dr'
,'Beauregard St'
,'Beauverde Ct'
,'Beckenham Dr'
,'Beckfield Ave'
,'Becky Lee Dr'
,'Bedford Dr'
,'Beech Harbor Ave'
,'Beech St'
,'Beechgrove Dr'
,'Beechwood Dr'
,'Bel Air Dr'
,'Bel Meadow Ave'
,'Belcaro Dr'
,'Beldart Ct'
,'Belfast Dr'
,'Bella Dr'
,'Bellarbor Dr'
,'Belle Angela Ave'
,'Belle Brittany Ave'
,'Belle Cherie Ave'
,'Belle Christi Dr'
,'Belle Famille Ave'
,'Bonnie Dr'
,'Bonnie Jean Dr'
,'Bontura Ct'
,'Booker St'
,'Boone Ave'
,'Bootsie Dr'
,'Bordeaux Dr'
,'Boreas Dr'
,'Boston St'
,'Bourbon Ave'
,'Bourgeois St'
,'Bowie Ave'
,'Bowman Ave'
,'Boyce Dr'
,'Boyd Ave'
,'Boylan Ave'
,'Bozeman Ave'
,'Bracewell Dr'
,'Braddock St'
,'Braden Patrick Dr'
,'Bradfield Ave'
,'Bradley St'
,'Bradmore Dr'
,'Brady St'
,'Braeburn Dr'
,'Braewood Ave'
,'Brakley Dr'
,'Bramble Dr'
,'Brame Dr'
,'Branchwood Ave'
,'Brandon Dr'
,'Brandon Lynn Dr'
,'Brandywine Dr'
,'Brashears St'
,'Breckenridge Ave'
,'Breman Dr'
,'Brent Ave'
,'Brent Ct'
,'Brentwood Dr'
,'Brentwood Dr'
,'Breton Blvd'
,'Breton Dr'
,'Bretshire Dr'
,'Brett Pl'
,'Brewster Ave'
,'Brianna Ave'
,'Briar Hollow Ave'
,'Briarlake Ave'
,'Briarplace Dr'
,'Briartrail Dr'
,'Briarwood Pl'
,'Brice St'
,'Bricksome Ave'
,'Brickyard Ln'
,'Brierwood Dr'
,'Brighton Ave'
,'Brightside Dr'
,'Brightside View Dr'
,'Brightview Ct'
,'Brillock Ave'
,'Bringhurst Ave'
,'Brinwood Ave'
,'Bristoe Ave'
,'Bristol Ave'
,'Britain Ave'
,'Brittany Dr'
,'Brittmore Ave'
,'Broad Magnolia Ct'
,'Broadmoor Ave'
,'Broadmoor Cir'
,'Broadmoor Ct'
,'Broadway St'
,'Brocade Dr'
,'Brocato Ave'
,'Brogdon Ln'
,'Brogdon Ln'
,'Broker Ave'
,'Bromley Dr'
,'Bronco Ave'
,'Bronzebush Ave'
,'Brook Spring Ave'
,'Brookcrest Ave'
,'Brookfield Ave'
,'Brookhaven Dr'
,'Brooklawn Dr'
,'Brookline Ave'
,'Brookmeade Dr'
,'Brooks Ave'
,'Brookshire Ave'
,'Brookwood Dr'
,'Broussard St'
,'Brownfields Dr'
,'Browning Dr'
,'Brownlee St'
,'Brownway Ln'
,'Bruce Alley'
,'Brunswick Ave'
,'Brutus Dr'
,'Bryans Crossing Ave'
,'Bryant Dr'
,'Buckeye Dr'
,'Buckingham Ave'
,'Buckley Ave'
,'Buena Vista Dr'
,'Buhler Dr'
,'Bull Run Dr'
,'Bungalow Ln'
,'Bunker Hill Dr'
,'Cabernet Dr'
,'Cable St'
,'Cabot Ave'
,'Caddo St'
,'Cadillac St'
,'Caesar Ave'
,'Cain St'
,'Cal Rd'
,'Calanne Ave'
,'Caldwell Ave'
,'California St'
,'Calion Dr'
,'Callahan St'
,'Calumet St'
,'Calverton Dr'
,'Cambridge St'
,'Camden St'
,'Camelia Ave'
,'Camelia Trace Dr'
,'Camelia Way Ct'
,'Camelio Ave'
,'Camelot Ave'
,'Cameo Ct'
,'Cameron Ave'
,'Cammy Ave'
,'Campanile Ct'
,'Campbell Dr'
,'Camphor Dr'
,'Campus Lake Rd'
,'Canada St'
,'Canal St'
,'Candace St'
,'Candlewood Ave'
,'Canebrake Dr'
,'Cannon St'
,'Canonicus St'
,'Canosa Ct'
,'Canterbury Dr'
,'Canterdale Ave'
,'Canyonland Dr'
,'Cape Hart Ct'
,'Cape Hatteras Dr'
,'Capistra Dr'
,'Capital Heights Ave'
,'Capitol Access Rd'
,'Capitol Ave'
,'Capitol Lake Dr'
,'Capri Dr'
,'Caprice Dr'
,'Cardeza Ave'
,'Cardiff Ave'
,'Cardigan Ave'
,'Cardinal St'
,'Carl Ave'
,'Carlene Ave'
,'Carleton Dr'
,'Carlotta St'
,'Carlsbad Dr'
,'Carmen Dr'
,'Carnifix Ct'
,'Carnouste Dr'
,'Carol Dr'
,'Carol Marie Dr'
,'Carolina St'
,'Caroljack Dr'
,'Carolyn Sue Dr'
,'Carondelet Ct'
,'Carr Alley'
,'Carriage Ct Dr'
,'Carriage Way'
,'Carrington Pl Ave'
,'Carrollton Ave'
,'Carter Ave'
,'Carver St'
,'Casa Grande Dr'
,'Casa Loma Dr'
,'Cascades Ave'
,'Cashel Ave'
,'Casper St'
,'Caspiana Ave'
,'Castile Ave'
,'Castille Rd'
,'Castle Hill Dr'
,'Castle Kirk Dr'
,'Castle Ridge St'
,'Castlebury Dr'
,'Castlewood Dr'
,'Catalina Ave'
,'Catalpa St'
,'Cate Ave'
,'Cathedral Dr'
,'Catherine St'
,'Catiline Pl'
,'Cato St'
,'Cavalier Dr'
,'Ceba Ln'
,'Cedar Ave'
,'Cedar Bend Ave'
,'Cedar Creek Dr'
,'Cedar Glen Dr'
,'Cedar Grove Dr'
,'Cedar Key Ave'
,'Cedar Lake Dr'
,'Cedar Line Dr'
,'Cedar Lodge Dr'
,'Cedar Park Ave'
,'Cedar Pointe Ave'
,'Cedar Ridge Ave'
,'Cedar Way'
,'Cedarbrook Ave'
,'Cedarcrest Ave'
,'Cedardale Ave'
,'Cedarlane Ave'
,'Celestial Dr'
,'Celtic Dr'
,'Centenary Dr'
,'Centerpointe Dr'
,'Centerway Blvd'
,'Central Pine Dr'
,'Central Rd'
,'Central Woods Ave'
,'Centurion Ave'
,'Century Ave'
,'Cezanne Ave'
,'Chablis Ave'
,'Chablis Ct'
,'Chairman Ave'
,'Chalice Dr'
,'Chalma Ave'
,'Chalmers St'
,'Championship Dr'
,'Chancellorsville Ave'
,'Chandler Dr'
,'Chaney Dr'
,'Chanticleer Ct'
,'Chantilly Ave'
,'Chapel View Ct'
,'Chapelwood Dr'
,'Char-a-banc Ave'
,'Chardonnay Ave'
,'Charing Way Ave'
,'Charington Ave'
,'Chariot Dr'
,'Charlene Dr'
,'Charles St'
,'Charleston Villa Dr'
,'Charlestown Ln'
,'Charlotte Dr'
,'Charmaine Ave'
,'Charter Pl'
,'Chasefield Ave'
,'Chatawa Dr'
,'Chateau Ct'
,'Chateau Dr'
,'Chatfield Ave'
,'Chatsworth St'
,'Chattanooga Dr'
,'Chaucer Dr'
,'Chelsea Dr'
,'Chelwood Ave'
,'Chenango Dr'
,'Chene Ave'
,'Cherokee St'
,'Cherry Hill Ave'
,'Cherry Oak Dr'
,'Cherry St'
,'Cherrydale Ave'
,'Cherryl Dr'
,'Cherrywood Dr'
,'Chesapeake Ave'
,'Chesterfield Dr'
,'Chestnut Dr'
,'Chestnut Oak Dr'
,'Chestnut St'
,'Chevalier Ave'
,'Chevelle Ct'
,'Chevelle Dr'
,'Cheyenne Dr'
,'Chickamauga Ave'
,'Chimneywood Ave'
,'Chinn St'
,'Chippendale Dr'
,'Chippenham Dr'
,'Chippewa St'
,'Chisholm Ave'
,'Choctaw Dr'
,'Chopin Dr'
,'Chuck Yeager Ave'
,'Churchill Ave'
,'Cicero Ave'
,'Cinquefoil Ave'
,'Citadel Dr'
,'Citiplace Ct'
,'Citiplace Dr'
,'Clairewood Ct'
,'Clairmont Ave'
,'Clara Dr'
,'Claret Ave'
,'Classique Dr'
,'Claus Cir'
,'Claybrook Dr'
,'Claycut Rd'
,'Clayton Ct'
,'Clayton Dr'
,'Clear Lake Ave'
,'Clear Oak Ave'
,'Clematis Dr'
,'Cleo Ct'
,'Cletus Dr'
,'Clifton Dr'
,'Clinton Ave'
,'Cloud Dr'
,'Cloudland Dr'
,'Clover Dr'
,'Clover Ridge Ave'
,'Cloverdale Ave'
,'Cloverhill Blvd'
,'Cloverland Ave'
,'Cloverland Ct'
,'Cloverland Park Dr'
,'Coates Crossing'
,'Cobblestone Ct'
,'Cocodrie Ave'
,'Cody Dr'
,'Coffee Rd'
,'Cold Harbour Ave'
,'Cold Water Creek Ct'
,'Cole Dr'
,'Coliseum Ave'
,'Colleen Ct'
,'College Dr'
,'College Hill Dr'
,'Collegiate Ct'
,'Collins Dr'
,'Colonel Allen Ct'
,'Colonel Gibson Cir'
,'Colonial Dr'
,'Colorado St'
,'Columbus Dunn Dr'
,'Comal Dr'
,'Conti Dr'
,'Continental Dr'
,'Convention St'
,'Conway Dr'
,'Conwood Ave'
,'Cook Dr'
,'Coolidge St'
,'Coot St'
,'Copperfield Ct'
,'Copperfield Dr'
,'Copperleaf Dr'
,'Copping Dr'
,'Cora Dr'
,'Coral Dr'
,'Corinth St'
,'Cork St'
,'Cormorant St'
,'Cornell Ave'
,'Corporate Blvd'
,'Cortana Pl'
,'Cortez Dr'
,'Costello Ln'
,'Cottage Dr'
,'Cottage Hill Dr'
,'Cottage Row Dr'
];