const from_to = [
    /*["University of New Orleans", "Canal at Tchoupitoulas"],
    ["Canal at Cemeteries", "French Market"],
    ["St. Claude + Elysian Fields","UPT Streetcar Bay 1"],
    ["Canal + N. Peters","Poland + St. Claude"],
    ["French Market Station", "Museum of Art"],
    ["Canal + Carondelet", "S. Carrollton + S. Claiborne"],
    ["Audubon Park", "Canal + Magazine"],
    ["Audubon Zoo", "Canal + Magazine"],
    ["Freret + Broadway", "S. Rampart + Canal"],
    ["Canal + Magazine", "S. Claiborne + Carrollton"],
    ["Orleans + City Park", "Louisiana + Tchoupitoulas"],
    ["Napoleon + Tchoupitoulas", "S. Rampart + Canal"],
    ["Basin + Iberville", "Audubon Zoo"],
    ["Leonidas + S. Claiborne", "Saratoga + Canal"],
    ["Cemeteries", "Veterans + Carrollton"],
    ["University of New Orleans", "Elk Place + Cleveland"],
    ["Southern + University (Park 2)", "S. Rampart + Canal"],
    ["Hayne + Vincent", "Orleans + City Park"],
    ["Bullard + Walmart", "Elk Place + Canal"],
    ["Michoud + Expedition", "Elk Place + Canal"],
    ["SUNO College of Business", "Elk Place + Cleveland"],
    ["St Maurice + St Claude", "Tulane + Loyola"],
    ["St Claude + Aycock", "S. Rampart + Canal"],
    ["Gentilly + Caton", "S. Carrollton + S. Claiborne"],
    ["Michoud + Chef Mentuer Highway", "+ Canal	Washington + S.Broad"],
    ["Tullis + Woodland", "Elk Place + Canal"],
    ["Opelousas + Heerman", "New Orleans Military Academy"],
    ["Elk Place + Canal", "Opelousas + Heerman"],
    ["Bennett + Berkley", "Canal St. Ferry"],
    ["Bennett + Berkley", "Elk Place + Canal"],
    ["Joe Yenni + W. Loyola", "Minor + Third St."],
    ["NO Airport Terminal Departures", "Elk Place + Canal"],

    ["Harlem", "Soho"],
    ["Washington Heights", "East Village"],
    ["Fort George", "East Village"],
    ["E 32 St", "The Cloisters"],
    ["Midtown", "GW Bridge"],
    ["Harlem", "14th Street"],
    ["West Village", "East Village"],
    ["Battery Parks City", "Kips Bay"],
    ["Harlem", "Columbus Circle"],
    ["Riverbank Park", "West Village"],
    ["Columbus Circle", "Abingdon Square"],
    ["Lower E Side", "Chelsea Piers"],
    ["Lower E Side", "Abingdon Square"],
    ["East Harlem", "South Ferry"],
    ["Lincoln Center", "South Ferry"],
    ["Lower East Side", "West Village"],
    ["Lower East Side", "Battery Parks City"],
    ["Yorkville", "Clinton"],
    ["United Nations", "42 St Pier"],
    ["42 St Pier", "East Side"],
    ["Midtown", "South Ferry"],
    ["East Side", "West Side"],
    ["Washington Heights", "East Midtown"],
    ["Inwood ", "East Harlem"]
    ["East Viilage", "Harlem"],
    ["East Harlem", "City Hall"],
    ["West Harlem", "Times Square"],
    ["East Harlem", "West Side"],
    ["Jackson Heights", "Penn Station"],

    ["Leolua", "Waipahu"],
    */["Leolua", "Kamehameha Pali Momi"]/*,
    ["Leolua", "Kamehameha Salt Lake"],
    ["Leolua", "Kalihi Transit Center"],
    ["Leolua", "Dillingham"],
    ["Leolua", "King Punchbowl"],
    ["Leolua", "Kapiolani Keeaumoku"],
    ["Leolua", "University of Hawaii-Manoa"],
    ["University of Hawaii-Manoa", "Kapiolani Keeaumoku"],
    ["University of Hawaii-Manoa", "King Punchbowl"],
    ["University of Hawaii-Manoa", "Dillingham"],
    ["University of Hawaii-Manoa", "Kalihi Transit Center"],
    ["University of Hawaii-Manoa", "Kamehameha Salt Lake"],
    ["University of Hawaii-Manoa", "Kamehameha Pali Momi"],
    ["University of Hawaii-Manoa", "Waipahu"],
    */
];